<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../ActivityExplorer.Core/ActivityExplorer.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Garmin.FIT.Sdk" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="ActivityExplorer.Tests" />
  </ItemGroup>
</Project>
